### ISSUE TITLE
fix anchors better

### ISSUE THREAD

**Issue by KungFuDonkey** [svsticky/intro-website-2016-2024#45]
anchors need a calculation for the jump to the anchors, because parallax scrolling messes with their location

**Comment by KungFuDonkey** [comment]
text anchors cant have refs made by react (so they can only have one ref which doesn't work with findDOMNode) so we will have to find a work around

**Comment by KungFuDonkey** [comment]
might be fixable by first going to the top of the screen and then going to the anchor

**Comment by Mstiekema** [comment]
The website currently has a lot of warnings which have to be fixed. These are also all related to anchors. Please look at [this](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-has-content.md). 50% of the issues can be fixed by renaming `ref` to `href`.
