### ISSUE TITLE
POST A-eskwadraat bijna-lid

### ISSUE THREAD

**Issue by Siem2l** [svsticky/intro-website-2016-2024#57]
A-eskwadraat require some basic information to make 'bijna-lid'-accounts for the new students. When a student registers on the site we should make a POST request to 
https://www.a-eskwadraat.nl/Leden/Intro/Aanmelden 

With this information in the body:
- email - Het emailadres van de student (UU)
- voornaam - De voornaam van de student
- voorletters - De voorletters van de student
- tussenvoegsel - Optioneel, tussenvoegsel van de student
- achternaam - De achternaam van de student
- geslacht - 'M'/'V'/'?' (Man/Vrouw/Onbekend of Anders)
- geboortedatum - In YYYY-mm-dd formaat
- studentnummer - Het studentnummer
- straat - De straat van de woonplaats
- huisnummer - Het huisnummer van de woonplaats
- postcode - De postcode van de woonplaats
- plaats - De naam van de woonplaats
- land - Optioneel, maar kan ook gewoon 'Nederland' of iets anders zijn
- mobiel - Gewoon het nummer
- studie - 'IC'/'IK'/'NA'/'WI'/'GT'/'WIT' (Informatica/Informatiekunde/Natuurkunde/Wiskunde/Gametechnologie/Wiskunde en Toepassingen)

Since this information is private there should also be a checkmark for students to allow sharing this data or not if they don't want to.

**Comment by THECASE99** [comment]
I will do this in the backend for the form. We should note that this is more information than we currently ask for. Do we want to ask for more information of can we leave these parts black for now?

**Comment by Riscky** [comment]
we're not going for this approach anymore, but we'll hand over the database :)
