### ISSUE TITLE
Add iframe for pretix enrollments

### ISSUE THREAD

**Issue by Mstiekema** [svsticky/intro-website-2016-2024#74]
We will be handling enrollment for the introduction through pretix. The enrollment website should be embeded directly into the website

**Comment by SilasPeters** [comment]
@Mstiekema @Riscky a PR which mentioned this issue is closed as 'outdated'. I assume that this issue should thus be closed as well?

**Comment by Riscky** [comment]
We have Pretix integrated on the current intro website indeed

**Comment by SilasPeters** [comment]
Thanks Rick
